Javascript modal | Max
max-cendalski/c1021-code-solutions pull request #45
Opened 2021-10-20 05:46 UTC by Korneliu

![javascript-modal](https://user-images.githubusercontent.com/25681013/138035172-3a91054e-6528-4019-b46e-ceb268502767.png)

2021-10-31 20:58 UTC, Korneliu commented
![javascript-modal](https://user-images.githubusercontent.com/25681013/139601000-9956bbc2-8de9-4e13-846e-3003e86ecb63.png)

FYI I only moved event.preventDefault() to the beginning of a function. Either way it's working .... I don't know why. I guess we'll talk about it on Monday :D

2021-11-03 22:34 UTC, codingcodymiller requested changes
I would love to see a gif of you clicking "NO" and the modal closing 🙏

2021-11-04 04:33 UTC, Korneliu commented
![javascript-modal](https://user-images.githubusercontent.com/25681013/140258435-14b97efc-27d5-4800-82ac-0a4194fdb039.png)

2021-11-16 17:08 UTC, codingcodymiller approved these changes

2021-11-16 18:24 UTC, merged