JavaScript bank | Max
max-cendalski/c1021-code-solutions pull request #61
Opened 2021-11-03 00:28 UTC by Korneliu

![javascript-bank](https://user-images.githubusercontent.com/25681013/139969584-df403acd-3cab-40b6-9dc4-1dfdebba0704.png)

2021-11-03 22:14 UTC, codingcodymiller requested changes

2021-11-03 22:14 UTC, codingcodymiller commented on javascript-bank/bank.js
> +    Account.getBalance += newAccount.deposit(balance);
Why are you trying to add/concatenate onto a function definition? Does this pass all the tests? I would think this would ruin `getBalance`

2021-11-04 05:46 UTC, Korneliu commented
![javascript-bank](https://user-images.githubusercontent.com/25681013/140264172-17b497de-22c6-4e57-93fc-27702e97fadf.png)

2021-11-16 17:10 UTC, codingcodymiller requested changes

2021-11-16 17:10 UTC, codingcodymiller commented on javascript-bank/bank.js
> +    Account.getBalance = newAccount.deposit(balance);
This is also incorrect. Is this passing all tests? You didn't tell me with your last update.

2021-11-16 17:11 UTC, codingcodymiller commented on javascript-bank/bank.js
> +    Account.getBalance = newAccount.deposit(balance);
You should change this line to just `newAccount.deposit(balance);`

2021-11-21 18:38 UTC, merged